---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/comments":
    post:
      summary: create comment
      parameters:
      - name: Authorization
        in: header
        type: string
        description: Authorization
      - name: comment
        in: body
        schema:
          type: object
          properties:
            comment:
              type: object
              properties:
                contribution_id:
                  type: integer
                text:
                  type: string
                replayedComment_id:
                  type: integer
                  nullable: true
      responses:
        '200':
          description: success
        '201':
          description: created
        '401':
          description: unauthorized
  "/comments/{id}/like":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    - name: Authorization
      in: header
      type: string
      description: Authorization
    put:
      summary: like comment
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '422':
          description: unprocessable_entity
  "/comments/{id}/dislike":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    - name: Authorization
      in: header
      type: string
      description: Authorization
    put:
      summary: dislike comment
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '422':
          description: unprocessable_entity
  "/comments/{id}/show_upvoted_comments":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show_upvoted_comments comment
      responses:
        '200':
          description: success
        '422':
          description: unprocessable_entity
  "/comments/{id}/show_comments":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show_comment comment
      responses:
        '200':
          description: success
        '422':
          description: unprocessable_entity
  "/comments/new":
    get:
      summary: new comment
      responses:
        '200':
          description: success
  "/comments/{id}":
    delete:
      summary: delete comment
      parameters:
      - name: Authorization
        in: header
        type: string
        description: Authorization
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '404':
          description: not_found
  "/contributions":
    get:
      summary: list contributions of type url
      tags:
      - Contributions
      responses:
        '200':
          description: success
    post:
      summary: create contribution
      tags:
      - Contributions
      parameters:
      - name: Authorization
        in: header
        type: string
        description: Authorization
      - name: contribution
        in: body
        schema:
          type: object
          properties:
            contribution:
              type: object
              properties:
                contribution_type:
                  type: string
                text:
                  type: string
                title:
                  type: string
                url:
                  type: string
      responses:
        '200':
          description: success
        '201':
          description: created
        '401':
          description: unauthorized
  "/contributions/{id}/like":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    - name: Authorization
      in: header
      type: string
      description: Authorization
    put:
      summary: like contribution
      tags:
      - Contributions
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '422':
          description: unprocessable_entity
  "/contributions/{id}/dislike":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    - name: Authorization
      in: header
      type: string
      description: Authorization
    put:
      summary: dislike contribution
      tags:
      - Contributions
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '422':
          description: unprocessable_entity
  "/contributions/show_news":
    get:
      summary: show_news contribution
      tags:
      - Contributions
      responses:
        '200':
          description: success
  "/contributions/show_ask":
    get:
      summary: show_ask contribution
      tags:
      - Contributions
      responses:
        '200':
          description: success
  "/contributions/{id}/show_user":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show_user contribution
      tags:
      - Contributions
      responses:
        '200':
          description: success
  "/contributions/{id}/show_upvoted_contributions":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show_upvoted_contributions contribution
      tags:
      - Contributions
      responses:
        '200':
          description: success
        '422':
          description: unprocessable_entity
  "/contributions/new":
    parameters:
    - name: Authorization
      in: header
      type: string
      description: Authorization
    get:
      summary: new contribution
      tags:
      - Contributions
      responses:
        '200':
          description: success
  "/contributions/{id}/edit":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: edit contribution
      tags:
      - Contributions
      responses:
        '200':
          description: success
  "/contributions/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show contribution
      tags:
      - Contributions
      responses:
        '200':
          description: success
    patch:
      summary: update contribution
      tags:
      - Contributions
      parameters:
      - name: Authorization
        in: header
        type: string
        description: Authorization
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
    put:
      summary: update contribution
      tags:
      - Contributions
      parameters:
      - name: Authorization
        in: header
        type: string
        description: Authorization
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
    delete:
      summary: delete contribution
      tags:
      - Contributions
      parameters:
      - name: Authorization
        in: header
        type: string
        description: Authorization
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '404':
          description: not_found
  "/":
    get:
      summary: list contributions of type url
      tags:
      - Contributions
      responses:
        '200':
          description: success
  "/users/{id}/edit":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: edit user
      tags:
      - Users
      parameters:
      - name: Authorization
        in: header
        type: string
        description: Authorization
      responses:
        '200':
          description: success
        '404':
          description: not_found
        '401':
          description: unauthorized
    put:
      summary: update user
      tags:
      - Users
      parameters:
      - name: Authorization
        in: header
        type: string
        description: Authorization
      - name: user
        in: body
        schema:
          type: object
          properties:
            user:
              type: object
              properties:
                about:
                  type: string
                email:
                  type: string
                max_visit:
                  type: integer
                min_away:
                  type: integer
                delay:
                  type: integer
                show_dead:
                  type: boolean
                no_procrast:
                  type: boolean
      responses:
        '200':
          description: success
        '404':
          description: not_found
        '401':
          description: unauthorized
  "/users/{id}/show":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: success
        '404':
          description: not_found
tags:
- name: Users
  description: User management
- name: Contributions
  description: Contribution management
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
